### ISSUE TITLE
How to add custom fields

### ISSUE THREAD

**Issue by jk3us** [iszelei/osticket-sdk#2]
I have some custom form fields on tickets that I am setting via the API.  After some tinkering, I found that this works.  Consider adding it to the docs?

```
$ticket = new Iszelei\OsTicketSDK\Ticket;
$ticket->setName($usersName)
    ->setEmail($email)
    ->setSubject($subject)
    ->setMessage($body)
    ->setTopicId(1);
$ticket->country = $usersCountry;
$created = $osTicket->createTicket($ticket);
```

If you have a custom field with the variable name "country" for tickets, this will populate it.  You might consider also adding a `setCustom('variable_name', 'value')` method on ticket to make this more explicit and clear.

**Comment by iszelei** [comment]
True, the "setCustom" method will be implemented in the near future. Thank you!
